name: PlatformIO Tests

on:
  push:
    branches:
      - main  # Run tests on push to the main branch
  pull_request:  # Run tests for pull requests

jobs:
  unit_tests:
    runs-on: ubuntu-latest  # Use Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify Python version

      - name: Install PlatformIO
        run: pip install platformio

      - name: Verify PlatformIO installation
        run: platformio --version

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Run PlatformIO unit tests
        run: pio test -e native

      - name: Generate Coverage Report
        run: |
          mkdir -p coverage
          lcov --directory .pio/build/native --capture --output-file coverage/coverage.info
          lcov --remove coverage/coverage.info '/usr/*' --output-file coverage/coverage.info
          lcov --list coverage/coverage.info

      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/coverage.info